### ISSUE TITLE
documentation improvments

### ISSUE THREAD

**Issue by gitshub** [dslackw/pysed#2]
Thank you for this excellent utility.  May I suggest some improvements to the documentation?        

1   At https://github.com/dslackw/pysed   it says  
        "“Command Line Tool Usage

pysed is utility that parses and transforms text

Usage: pysed [OPTION] {pattern} {repl} {lines/max/flag} [input-file] “"   

```
which seems much clearer than that section on page https://pypi.python.org/pypi/pysed/0.3.1#python-regex-flags , which says     

    "Command Line Tool Usage
```

Usage: pysed [OPTION] {pattern} {repl} {max} {flag} [input-file]
"  
    so I recommend the latter be replaced with the former.  
    Fortunately, the “man” page already has the better version.     

2   It would be extremely helpful to “spell out in English” a couple of examples, as near as possible to the “usage” sections mentioned above (including the one on the “man” page).  
    This would help clarify the meaning of “lines/max/flag”.  
    The examples of cats, dogs, and fish are good (and cute too!), but someone may give up before reading through them, so  I recommend adding something like this just below the “usage” line:     

```
    For example, the command    
        pysed -r "is" "IS" 1,7/1 text.txt 
    means   
        In lines 1 and 7 of file “text.txt”, replace a maximum of 1 occurrence per line of `is^ by `IS.  Just write to SYSOUT (do not overwite the file). Use quotes around the strings, as shown. 
    An example of using a flag is   
        `echo "/usr/local/bin" | pysed -r "/LoCal" "" //IGNORECASE
```

3   In the “man” page, instead of  
         “ If the pattern isn’t found, string is returned unchanged. repl can be a string or a  function;  if  it  is a string, any backslash escapes in it ise concessed.”  
    it should say  
         “ If the pattern isn’t found, string is returned unchanged. repl can be a string or a function; if it is a string, any backslash escapes in it are processed.”       

4   The “Use as piping” section of https://github.com/dslackw/pysed has helpful examples which are lacking from https://pypi.python.org/pypi/pysed/0.3.1#python-regex-flags .  I recommend the latter be replaced with the former.

**Comment by dslackw** [comment]
Thank you for this report. If you want you can do a pull requests :)
